# Circuitos Electorales de Argentina
## Notebook para explorar los GeoJSON del repositorio `circuitos_electorales_AR`.
## Genera una tabla con los circuitos por provincia y un resumen de totales.

In [1]:
import json
import glob
import pandas as pd
from pathlib import Path
from IPython.display import display

In [2]:

# ──────────────────────────────────────────────
# Configuración — ajustá este path si es necesario
# ──────────────────────────────────────────────
GEOJSON_DIR = Path("geojson")   # relativo a donde esté el notebook dentro del repo

In [3]:

# Mapa codprov → nombre de provincia (orden oficial Argentina)
PROVINCIAS = {
    "01": "Ciudad Autónoma de Buenos Aires",
    "02": "Buenos Aires",
    "03": "Catamarca",
    "04": "Córdoba",
    "05": "Corrientes",
    "06": "Chaco",
    "07": "Chubut",
    "08": "Entre Ríos",
    "09": "Formosa",
    "10": "Jujuy",
    "11": "La Pampa",
    "12": "La Rioja",
    "13": "Mendoza",
    "14": "Misiones",
    "15": "Neuquén",
    "16": "Río Negro",
    "17": "Salta",
    "18": "San Juan",
    "19": "San Luis",
    "20": "Santa Cruz",
    "21": "Santa Fe",
    "22": "Santiago del Estero",
    "23": "Tucumán",
    "24": "Tierra del Fuego",
}

# Mapa nombre de archivo (sin extensión, uppercase) → codprov
# Cubre variantes de nombre que pueden aparecer en el repo
ARCHIVO_A_CODPROV = {
    "CABA":                      "01",
    "CIUDAD_AUTONOMA_DE_BUENOS_AIRES": "01",
    "BUENOS_AIRES":              "02",
    "CATAMARCA":                 "03",
    "CORDOBA":                   "04",
    "CORRIENTES":                "05",
    "CHACO":                     "06",
    "CHUBUT":                    "07",
    "ENTRE_RIOS":                "08",
    "FORMOSA":                   "09",
    "JUJUY":                     "10",
    "LA_PAMPA":                  "11",
    "LAPAMPA":                   "11",
    "LA_RIOJA":                  "12",
    "MENDOZA":                   "13",
    "MISIONES":                  "14",
    "NEUQUEN":                   "15",
    "RIO_NEGRO":                 "16",
    "SALTA":                     "17",
    "SAN_JUAN":                  "18",
    "SAN_LUIS":                  "19",
    "SANTA_CRUZ":                "20",
    "SANTA_FE":                  "21",
    "SANTIAGO_DEL_ESTERO":       "22",
    "TUCUMAN":                   "23",
    "TIERRA_DEL_FUEGO":          "24",
}

In [4]:
def codprov_desde_archivo(nombre_archivo: str) -> str:
    """Infiere el codprov a partir del nombre del archivo GeoJSON."""
    clave = Path(nombre_archivo).stem.upper()
    return ARCHIVO_A_CODPROV.get(clave, None)

In [5]:
# %%
# ──────────────────────────────────────────────
# 1. Listar archivos GeoJSON locales
# ──────────────────────────────────────────────
archivos = sorted(GEOJSON_DIR.glob("*.geojson"))
print(f"Archivos encontrados: {len(archivos)}")
for f in archivos:
    print(f"  {f.name}")

Archivos encontrados: 24
  CABA.geojson
  CATAMARCA.geojson
  CHACO.geojson
  CHUBUT.geojson
  CORDOBA.geojson
  CORRIENTES.geojson
  ENTRERIOS.geojson
  FORMOSA.geojson
  JUJUY.geojson
  LAPAMPA.geojson
  LA_RIOJA.geojson
  MENDOZA.geojson
  MISIONES.geojson
  NEUQUEN.geojson
  PBA.geojson
  RIO_NEGRO.geojson
  SALTA.geojson
  SANLUIS.geojson
  SANTACRUZ.geojson
  SANTAFE.geojson
  SANTIAGO_DEL_ESTERO.geojson
  SAN_JUAN.geojson
  TIERRA_DEL_FUEGO.geojson
  TUCUMAN.geojson

In [6]:

# ──────────────────────────────────────────────
# 2. Leer todos los GeoJSON e iterar features
# ──────────────────────────────────────────────
registros = []

for archivo in archivos:
    with open(archivo, encoding="utf-8") as f:
        gj = json.load(f)

    for feature in gj.get("features", []):
        props = feature.get("properties", {})

        # Normalizar nombres de columnas (por si hay variaciones de mayúsculas)
        props_lower = {k.lower(): v for k, v in props.items()}

        circuito = props_lower.get("circuito")
        coddepto = str(props_lower.get("coddepto", "")).zfill(3)

        # Prioridad: codprov del archivo → fallback al nombre del archivo
        _raw = props_lower.get("codprov")
        codprov_prop = str(_raw).zfill(2) if _raw not in (None, "", "0", 0) else "00"
        codprov = (
            codprov_prop
            if codprov_prop not in ("00", "")
            else codprov_desde_archivo(archivo.name) or "??"
        )

        registros.append({
            "archivo":   archivo.name,
            "codprov":   codprov,
            "provincia": PROVINCIAS.get(codprov, f"Desconocida ({codprov})"),
            "coddepto":  coddepto,
            "circuito":  circuito,
        })

df = pd.DataFrame(registros)
print(f"Total de circuitos cargados: {len(df)}")

# Diagnóstico: archivos que no pudieron resolverse
sin_prov = df[df["codprov"] == "??"]["archivo"].unique()
if len(sin_prov):
    print(f"\n⚠️  Archivos sin provincia resuelta — agregá su clave al diccionario ARCHIVO_A_CODPROV:")
    for f in sin_prov:
        print(f"  '{Path(f).stem.upper()}': '??'  ← reemplazá ?? por el codprov correcto")

Total de circuitos cargados: 5589

In [7]:
# %%
# ──────────────────────────────────────────────
# 3. Tabla detallada por provincia
# ──────────────────────────────────────────────
print("=" * 60)
print("CIRCUITOS POR PROVINCIA — DETALLE")
print("=" * 60)

for prov_nombre, grupo in df.groupby("provincia", sort=True):
    circuitos = sorted(grupo["circuito"].dropna().unique().tolist())
    tabla = pd.DataFrame({
        "#":        range(1, len(circuitos) + 1),
        "Circuito": circuitos,
    }).set_index("#")

    print(f"\n{'─'*50}")
    print(f"  {prov_nombre}  (codprov: {grupo['codprov'].iloc[0]})")
    print(f"  Total circuitos: {len(circuitos)}")
    print(f"{'─'*50}")
    display(tabla)

============================================================
CIRCUITOS POR PROVINCIA — DETALLE
============================================================

──────────────────────────────────────────────────
  Buenos Aires  (codprov: 02)
  Total circuitos: 1066
──────────────────────────────────────────────────

     Circuito
#
1       00001
2       00002
3       00003
4       00004
5       00005
...       ...
1062    0973A
1063    0975A
1064    0975B
1065    1011A
1066    1013A

[1066 rows x 1 columns]

──────────────────────────────────────────────────
  Catamarca  (codprov: 03)
  Total circuitos: 155
──────────────────────────────────────────────────

    Circuito
#
1      00001
2      00002
3      00003
4      00004
5      00005
..       ...
151    00151
152    00152
153    00153
154    00154
155    0044A

[155 rows x 1 columns]

──────────────────────────────────────────────────
  Chaco  (codprov: 06)
  Total circuitos: 153
──────────────────────────────────────────────────

    Circuito
#
1      00001
2      00002
3      00003
4      00004
5      00006
..       ...
149    0135A
150    0135B
151    0135C
152    0138A
153    0138B

[153 rows x 1 columns]

──────────────────────────────────────────────────
  Chubut  (codprov: 07)
  Total circuitos: 115
──────────────────────────────────────────────────

    Circuito
#
1      00001
2      00002
3      00003
4      00004
5      00005
..       ...
111    0050B
112    0054A
113    0054B
114    0058A
115    0063A

[115 rows x 1 columns]

──────────────────────────────────────────────────
  Ciudad Autónoma de Buenos Aires  (codprov: 01)
  Total circuitos: 167
──────────────────────────────────────────────────

    Circuito
#
1      00001
2      00002
3      00003
4      00004
5      00005
..       ...
163    00163
164    00164
165    00165
166    00166
167    00167

[167 rows x 1 columns]

──────────────────────────────────────────────────
  Corrientes  (codprov: 05)
  Total circuitos: 170
──────────────────────────────────────────────────

    Circuito
#
1      00001
2      00002
3      00003
4      00004
5      00005
..       ...
166    0105A
167     0107
168    0117A
169    0128A
170    0130A

[170 rows x 1 columns]

──────────────────────────────────────────────────
  Córdoba  (codprov: 04)
  Total circuitos: 626
──────────────────────────────────────────────────

      Circuito
#
1        00001
2        00002
3        00003
4        00004
5        00005
..         ...
622      0397A
623   sindatos
624   zonagris
625  zonagris/
626  zonaincon

[626 rows x 1 columns]

──────────────────────────────────────────────────
  Entre Ríos  (codprov: 08)
  Total circuitos: 318
──────────────────────────────────────────────────

    Circuito
#
1      00001
2      00002
3      00003
4      00004
5      00005
..       ...
314    0174A
315    0195A
316    0202A
317    0213A
318    0304A

[318 rows x 1 columns]

──────────────────────────────────────────────────
  Formosa  (codprov: 09)
  Total circuitos: 107
──────────────────────────────────────────────────

    Circuito
#
1      00001
2      00002
3      00003
4      00004
5      00005
..       ...
103    0083B
104    0083C
105    0084A
106    0084B
107    0084C

[107 rows x 1 columns]

──────────────────────────────────────────────────
  Jujuy  (codprov: 10)
  Total circuitos: 146
──────────────────────────────────────────────────

    Circuito
#
1      00001
2      00002
3      00003
4      00004
5      00005
..       ...
142    0126A
143    0126B
144    0126C
145    0127A
146    0127B

[146 rows x 1 columns]

──────────────────────────────────────────────────
  La Pampa  (codprov: 11)
  Total circuitos: 89
──────────────────────────────────────────────────

   Circuito
#
1     00001
2     00002
3     00003
4     00004
5     00005
..      ...
85    00093
86    00094
87    00095
88    0019A
89    0039A

[89 rows x 1 columns]

──────────────────────────────────────────────────
  La Rioja  (codprov: 12)
  Total circuitos: 146
──────────────────────────────────────────────────

    Circuito
#
1      00003
2      00004
3      00007
4      00010
5      00013
..       ...
142    0062A
143    0062B
144    0062C
145    0062D
146    0062E

[146 rows x 1 columns]

──────────────────────────────────────────────────
  Mendoza  (codprov: 13)
  Total circuitos: 192
──────────────────────────────────────────────────

    Circuito
#
1      00001
2      00002
3      00003
4      00004
5      00005
..       ...
188    0107B
189    0107C
190    0117A
191    0127A
192    0134A

[192 rows x 1 columns]

──────────────────────────────────────────────────
  Misiones  (codprov: 14)
  Total circuitos: 89
──────────────────────────────────────────────────

   Circuito
#
1     00001
2     00002
3     00003
4     00004
5     00005
..      ...
85    0061A
86    0061B
87    0075A
88    0076A
89    0082A

[89 rows x 1 columns]

──────────────────────────────────────────────────
  Neuquén  (codprov: 15)
  Total circuitos: 156
──────────────────────────────────────────────────

    Circuito
#
1      00001
2      00008
3      00011
4      00015
5      00016
..       ...
152    01610
153    01620
154    01630
155    01640
156    01650

[156 rows x 1 columns]

──────────────────────────────────────────────────
  Río Negro  (codprov: 16)
  Total circuitos: 151
──────────────────────────────────────────────────

    Circuito
#
1      00002
2      00003
3      00004
4      00007
5      00009
..       ...
147    06520
148    06521
149    06522
150    06523
151    06524

[151 rows x 1 columns]

──────────────────────────────────────────────────
  Salta  (codprov: 17)
  Total circuitos: 315
──────────────────────────────────────────────────

    Circuito
#
1     00012C
2      0001A
3      0001B
4      0001C
5      0001D
..       ...
311    0099C
312    0100A
313    0101A
314    0102A
315    0103A

[315 rows x 1 columns]

──────────────────────────────────────────────────
  San Juan  (codprov: 18)
  Total circuitos: 146
──────────────────────────────────────────────────

    Circuito
#
1      00001
2      00002
3      00003
4      00004
5      00005
..       ...
142    0093A
143    0094A
144    0110A
145    0113A
146    0114A

[146 rows x 1 columns]

──────────────────────────────────────────────────
  San Luis  (codprov: 19)
  Total circuitos: 136
──────────────────────────────────────────────────

    Circuito
#
1      00002
2      00003
3      00004
4      00006
5      00007
..       ...
132    1008C
133    1008D
134    1008E
135    3001A
136    3001B

[136 rows x 1 columns]

──────────────────────────────────────────────────
  Santa Cruz  (codprov: 20)
  Total circuitos: 33
──────────────────────────────────────────────────

   Circuito
#
1     00001
2     00002
3     00003
4     00004
5     00005
6     00006
7     00008
8     00009
9     00010
10    00011
11    00012
12    00013
13    00014
14    00015
15    00016
16    00017
17    00018
18    00019
19    0001A
20    00020
21    00021
22    0004A
23    0005A
24    0006A
25    0008A
26    0012A
27    0012B
28    0013A
29    0014A
30    0015A
31    0016A
32    0021A
33    0021B

──────────────────────────────────────────────────
  Santa Fe  (codprov: 21)
  Total circuitos: 525
──────────────────────────────────────────────────

    Circuito
#
1      00001
2      00002
3      00003
4      00004
5      00005
..       ...
521    0420A
522    0422A
523    0422B
524    0425A
525    0425B

[525 rows x 1 columns]

──────────────────────────────────────────────────
  Santiago del Estero  (codprov: 22)
  Total circuitos: 257
──────────────────────────────────────────────────

    Circuito
#
1      00001
2      00002
3      00003
4      00004
5     00004A
..       ...
253    0190A
254    0193A
255    0195A
256    0215A
257    0224A

[257 rows x 1 columns]

──────────────────────────────────────────────────
  Tierra del Fuego  (codprov: 24)
  Total circuitos: 25
──────────────────────────────────────────────────

   Circuito
#
1      0004
2      0008
3      0010
4      0011
5      0012
6      0013
7      0014
8      0016
9      0018
10     0021
11     0101
12     0102
13     0103
14     0104
15     0105
16     0106
17     0107
18     0108
19     0109
20     0110
21     0111
22     0112
23     0113
24     0210
25     0221

──────────────────────────────────────────────────
  Tucumán  (codprov: 23)
  Total circuitos: 274
──────────────────────────────────────────────────

    Circuito
#
1      00001
2      00002
3      00003
4      00004
5      00005
..       ...
270    0216A
271    0223A
272    0223B
273    0227A
274    0228A

[274 rows x 1 columns]

In [8]:
# %%
# ──────────────────────────────────────────────
# 4. Tabla resumen: cantidad de circuitos por provincia
# ──────────────────────────────────────────────
resumen = (
    df.groupby(["codprov", "provincia"])["circuito"]
    .nunique()
    .reset_index()
    .rename(columns={"circuito": "total_circuitos"})
    .sort_values("codprov")
    .reset_index(drop=True)
)
resumen.index += 1

print("\n" + "=" * 60)
print("RESUMEN: TOTAL DE CIRCUITOS POR PROVINCIA")
print("=" * 60)
display(resumen)

print(f"\nTotal provincias/distritos: {len(resumen)}")
print(f"Total circuitos (país):     {resumen['total_circuitos'].sum()}")

============================================================
RESUMEN: TOTAL DE CIRCUITOS POR PROVINCIA
============================================================

   codprov                        provincia  total_circuitos
1       01  Ciudad Autónoma de Buenos Aires              167
2       02                     Buenos Aires             1066
3       03                        Catamarca              155
4       04                          Córdoba              626
5       05                       Corrientes              170
6       06                            Chaco              153
7       07                           Chubut              115
8       08                       Entre Ríos              318
9       09                          Formosa              107
10      10                            Jujuy              146
11      11                         La Pampa               89
12      12                         La Rioja              146
13      13                          Mendoza              192
14      14                         Misiones               89
15      15                          Neuquén              156
16      16                        Río Negro              151
17      17                            Salta              315
18      18                         San Juan              146
19      19                         San Luis              136
20      20                       Santa Cruz               33
21      21                         Santa Fe              525
22      22              Santiago del Estero              257
23      23                          Tucumán              274
24      24                 Tierra del Fuego               25

Total provincias/distritos: 24
Total circuitos (país):     5557

In [9]:
# ──────────────────────────────────────────────
# 5. (Opcional) Exportar a CSV
# ──────────────────────────────────────────────
df.to_csv("circuitos_detalle.csv", index=False)
resumen.to_csv("circuitos_resumen.csv", index=False)
print("Archivos exportados: circuitos_detalle.csv y circuitos_resumen.csv")

Archivos exportados: circuitos_detalle.csv y circuitos_resumen.csv